/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#006c4a',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary': '#006c49',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#00685f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#008378',
        'on-tertiary-container': '#f4fffc',
        'tertiary-fixed': '#89f5e7',
        'tertiary-fixed-dim': '#6bd8cb',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#005049',
        'primary': '#006948',
        'on-primary': '#ffffff',
        'primary-container': '#00855d',
        'on-primary-container': '#f5fff7',
        'primary-fixed': '#85f8c4',
        'primary-fixed-dim': '#68dba9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#005137',
        'inverse-primary': '#68dba9',
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3d4a42',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#6d7a72',
        'outline-variant': '#bccac0',
        'surface-variant': '#d3e4fe',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontWeight: {
        'label-sm': '700',
        'label-md': '600',
        'label-lg': '600',
        'headline-sm': '600',
        'headline-lg-mobile': '700',
      },
      spacing: {
        gutter: '1rem',
        'gutter-sm': '0.75rem',
        'gutter-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
      },
      fontSize: {
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '700', letterSpacing: '0.04em' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'price-hero': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'price-unit': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0px 1px 3px rgba(15, 23, 42, 0.04), 0px 6px 16px -4px rgba(15, 23, 42, 0.06)',
        float: '0px 4px 6px -1px rgba(15, 23, 42, 0.05), 0px 12px 24px -4px rgba(5, 150, 105, 0.08)',
        modal: '0px 20px 25px -5px rgba(15, 23, 42, 0.1), 0px 8px 10px -6px rgba(15, 23, 42, 0.04)',
      },
      keyframes: {
        scanline: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(180px)' },
        },
      },
      animation: {
        scanline: 'scanline 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};